- protocols/teamspeak3.js
virtualserver_name and virtualserver_maxclients
> Quick Fix For Name and MaxPlayers for Teamspeak 3

- README.md
- games.txt
- protocols/core.js
- protocols/quake2.js
Just added the game config for ARK: Survival Evolved
> Added ARK: Survival Evolved, Quake2 fixes (w/Compatibility)

- games.txt
> Updated Unturned for the latest version

- README.md
- games.txt
Added Hurtworld on valve protocol for my own use figured I would request too 👍 
http://store.steampowered.com/app/393420/
Example output from test server:
`{"name":"Test Server","map":"diemensland","password":false,"raw":{"protocol":17,"folder":"hurtworld","game":"Hurtworld","steamappid":0,"numplayers":0,"numbots":0,"listentype":"d","environment":"l","secure":1,"version":"41","port":12871,"steamid":"xxxxxxxxxxxxxxxxx","gameid":"393420","rules":{"eac":"True","gametype":"41","lastwipe":"1476621201","lootmode":"BackpackOnlyWithInfamy","nextwipe":"-1","rpmc":"0"}},"maxplayers":20,"players":[],"bots":[],"query":{"host":"hwserver.example.com","address":"xxx.xxx.xxx.xxx","port":12881,"port_query":12881,"type":"hurtworld","pretty":"Hurtworld"}}`
> Added Hurtworld

- README.md
- games.txt
> Add support for Conan Exiles & Primal Carnage: Extinction

- README.md
- games.txt
> Added GoldenEye:Source using Valve protocol

- README.md
- games.txt
Added these since both use valve protocol.
> Added Rising Storm 2 and Hell Let Loose

- README.md
- games.txt
Rel: https://github.com/sonicsnes/node-gamedig/issues/158
Found some time to do it myself. Hope this should do the trick.
> Add support for Mordhau

- protocols/minecraftvanilla.js
> Fix wrong player count in minecraftvanilla protocol

- README.md
- bin/gamedig.js
- games.txt
- protocols/discord.js
Add the discord protocol as described in #156 
Tested locally ✔️ 
I had to override DNSResolver as the address parsed is a discord ID and not a hostname.
I also changed the bin file as when I was passing snowflake IDs minimist was parsing them as integers, which would later cause errors (I just forced _ argument to be string).
> Add discord protocol

- lib/Results.js
the 2 bugfixes cherry picked from the other pr
> bugfix for Players/Results

- README.md
- games.txt
"Project Zomboid is the ultimate in zombie survival. Alone or in MP: you loot, build, craft, fight, farm and fish in a struggle to survive. A hardcore RPG skillset, a vast map, massively customisable sandbox and a cute tutorial raccoon await the unwary. So how will you die? All it takes is a bite.."
> Add support for Project Zomboid

- README.md
Hey @mmorrisontx!
I've gathered some of the information we discussed in these issues https://github.com/gamedig/node-gamedig/issues/232 and https://github.com/gamedig/node-gamedig/issues/234, and added them as a new section in the README file.
Also, I've added the `requestRules` in more examples, because it felt like was a bit hidden only inside the Valve protocol section.
Let me know what do you think!
Best
> Add additional notes for DayZ and make requestRules more evident

- protocols/valve.js
Hello @mmorrisontx!
Here's a PR with additional server information for DayZ, as we discussed at this issue: https://github.com/gamedig/node-gamedig/issues/232
Let me know if it makes sense!
All the best
> Parse additional dayz tags: first person, dlc enabled and time

- README.md
I often use gamedig just like that, I thought it would be useful to have it in the readme :)
> Add npx usage in the README

- protocols/valve.js
https://github.com/gamedig/node-gamedig/issues/294
> Fix wrong filter for "Max Players" for CSGO

- protocols/valve.js
Added according to https://steamdb.info/app/<appid> info. Figured I might as well complete the list of used AppIds.
> Use enum for all AppIds

- README.md
- games.txt
Another simple one. From #247 raised by @dgibbs64.
> Add support for Day of Dragons

- README.md
- games.txt
Another from dug up from the open issues, this one from LinuxGSM_'s @dgibbs64. Server listens on 7950 (game) and 7951 (query).
> Add support for Survive the Nights

- README.md
- games.txt
Last one for today. Requested by @CosminPerRam in #312.
> Add support for Risk of Rain 2

- README.md
- games.txt
Guess what: Valve protocol. Game/query port is 27004.
38.2.8.142:27004|Colony Survival|00.09.00.041
170.103.58.215:27004|Colony Survival|00.09.00.037
96.27.207.170:27004|Colony Survival|00.09.00.041
107.182.230.219:27004|Colony Survival|00.09.00.039
107.182.230.232:27004|Colony Survival|00.09.00.039
144.217.10.108:27004|Colony Survival|00.09.00.039
174.118.202.67:27004|Colony Survival|00.09.00.037
58.7.203.247:27004|Colony Survival|00.09.00.041
180.150.63.169:27004|Colony Survival|00.09.00.041
220.233.169.124:27004|Colony Survival|00.09.00.039
> Add support for Colony Survival

- CHANGELOG.md
- GAMES_LIST.md
- games.txt
> Add Creativerse (2017) support.

- CHANGELOG.md
- GAMES_LIST.md
- games.txt
> Add `The Isle` support.

- CHANGELOG.md
- GAMES_LIST.md
- games.txt
- protocols/eco.js
- protocols/index.js
> Add `Eco` (2018) support.

- CHANGELOG.md
- GAMES_LIST.md
- games.txt
Add Support for Core Keeper
port: 1234
queryport: 1235
> Add Core Keeper support

- CHANGELOG.md
- GAMES_LIST.md
- games.txt
We already have the sequel so why not the first one.
Adds support for [The Forest](https://store.steampowered.com/app/242760/The_Forest/).
Valve protocol, default port 27015, default query port +1.
> Add The Forest (2014) support.

- CHANGELOG.md
- GAMES_LIST.md
- games.txt
Adds support for [Operation: Harsh Doorstop](https://store.steampowered.com/app/736590/Operation_Harsh_Doorstop/).
Valve protocol, port 7777, query port 27005.
> Add Operation: Harsh Doorstop support.

- CHANGELOG.md
- GAMES_LIST.md
- games.txt
Adds support for [Insurgency: Modern Infantry Combat](https://store.steampowered.com/app/17700/INSURGENCY_Modern_Infantry_Combat/).
Valve protocol, query port and game port: 27015.
> Add Insurgency: Modern Infantry Combat support.

- .github/workflows/deno.yml
- .gitignore
This PR aims to add basic Deno checking to CI to be sure we don't break anything Deno related.
> Add Deno to CI

- CHANGELOG.md
- GAMES_LIST.md
- games.txt
> Add The Front support.

- CHANGELOG.md
- GAMES_LIST.md
- games.txt
> Add support for San Andreas OpenMP

- .github/workflows/deno.yml
- .github/workflows/node.yml
- README.md
Uses `paths` on the CI files to make jobs not run if they aren't needed.
> feat: Use paths on CI to speed it up

- CHANGELOG.md
- games.txt
- package-lock.json
- package.json
- protocols/asa.js
- protocols/epic.js
- protocols/index.js
With this modification it will also be possible to add support for other games that use EOS, to do this you only need to obtain the following credentials for each game:
- client_id
- client_secret
- deployment_id
Closes: #396 and #395 
I am open to any questions or suggestions about this PR 😁
- Only the server IP is used in the query, after which the API returns all servers at that IP.
- Then the list is filtered by the server port that was provided in the query
- The game does not have a query port.
My unofficial server:
```js
import GameDig from '../lib/index.js'
GameDig.query({
type: 'asa',
address: '189.90.255.6',
port: '7805'
}).then((state) => {
console.log(state)
}).catch((error) => {
console.log(`Server is offline, error: ${error}`)
})
```
```js
Results {
name: 'BR PVE TribuFu 5x …
```
> Add support for ARK: Survival Ascended using EOS protocol

- package-lock.json
- package.json
- protocols/epic.js
#402 added axios but we use got, this PR replaces its usage and removes axios.
> feat: remove axios from dependencies

- GAMES_LIST.md
Fixed not working sd2d to sdtd, which is working
> fixed 7 Days to die ID

- CHANGELOG.md
- games.txt
> fix: post scriptum not being on the valve protocol

- CHANGELOG.md
- protocols/minecraftvanilla.js
> Add support for the Minecraft BCC mod

- CHANGELOG.md
- GAMES_LIST.md
- games.txt
- protocols/eldewrito.js
Add support for ElDewrito, removed default assignments, rebased with recent changes, added newline to end of eldewrito.js.
> Add ElDewrito - 4.3.0

- CHANGELOG.md
- GAMES_LIST.md
- lib/games.js
- protocols/eldewrito.js
- protocols/index.js
- protocols/minecraftvanilla.js
This adds the changes made in #424, shall it be merged after it is released.
> Backport 4.3.0 changes into master

- lib/games.js
> fix: add -1 offset to Rising World

- GAMES_LIST.md
- lib/games.js
This PR would be the final one before releasing the next major version.
It consists of 3 parts ('*why?*', look at the end):
1. Extract release year from the game names:  
Suppose we have `Minecraft (2009)`, some users might not want the release year in the name, and making a workaround to extract it is a bit annoying for something that could be separated (opposed to the current game name rules in `CONTRIBUTING.md`, I'll revise it), so, we have removed it from the name (for those that had) and a new field called `release_year` has been added the the game structure, this field needs to be populated for those that do not have it.
2. Names refactor:  
Some games do not have their names correctly set, we'll need to revise all of them hand by hand (same goes for getting the release years for …
> Games IDs and names refactor, extract release year.

- tools/generate_games_list.js
Quick fix to add DayZ as a Valve protocol in the games list.
> fix: Add DayZ to Valve protocol in games list

- README.md
Hey! I've updated our README with some new info:
- Updated with Markdown Tables, for better visualization of each parameter
- Split into Required and Optional fields, for easier understanding
- Updated general descriptions with new info
- Added links for `GAMES_LIST.md` where needed
- Removed extra characters for smoother reading
This is 100% not needed, but I figure it could use an overall cleaner look.
Let me know your thoughts and I'll update everything accordingly! ✨
Thank you! (:
> chore: Cleaner and updated README

- bin/gamedig.js
Attempts on making the CLI code a bit more cleaner.
Even with these changes I still think it doesn't look that well, open for suggestions.
> chore: cleaner cli

- GAMES_LIST.md
- lib/games.js
Add missing notes in the `GAMES_LIST.md`
> chore: update games list

- tools/attempt_protocols.js
Pull protocol list from `/protocols/index.js` and adds to `/tools/attempt_protocols.js`
> feat(tools/attempt): test against all protocols

- CHANGELOG.md
- README.md
- bin/gamedig.js
- lib/QueryRunner.js
Closes #479.
Also adds an option to disable this.
> feat: breadth attempt order

- CHANGELOG.md
- lib/games.js
Quick update on `V Rising`. It closes this issue https://github.com/gamedig/node-gamedig/issues/438.
> feat: add new port to V Rising

- CHANGELOG.md
- GAMES_LIST.md
- lib/games.js
> feat: add Unreal 2: The Awakening - XMP support

- CHANGELOG.md
- GAMES_LIST.md
- lib/games.js
Closes #467.
There is something going on with players:
Querying 89.163.221.1:26001 (normal response):
Querying 168.119.137.110:
(players names are switched up with what it seems to be teams)
> feat: add xonotic support

- tools/attempt_protocols.js
Just a quick add of a successful message for the `attempt_protocols.js` tool.
> chore: Add tool attempt success log message

- CHANGELOG.md
- GAMES_LIST.md
- lib/games.js
- protocols/epic.js
- protocols/index.js
- protocols/theisleevrima.js
Support for The Isle Evrima using EOS protocol.
Closes #500 
I also moved the server and map name assignment to the specific protocol of The Isle.
It will still be necessary to modify the ASA and Palworld protocols to obtain this correct attribute data, I omitted this from this PR so as not to mix the games in the same modification.
Keep in mind that there are servers with the legacy version of The Isle, which do not work with this protocol, check if you are testing with a server of the correct version.
A random official server:
```js
GameDig.query({
type: 'theisleevrima',
host: '50.18.155.230',
port: '7777'
}).then((state) => {
console.log(JSON.stringify(state))
}).catch((error) => {
console.log(`Server is offline, error: ${error}`)
})
```
```json
{
"name": "Official Evrima - NA 6", …
```
> feat: add support for The Isle Evrima

- CHANGELOG.md
- protocols/epic.js
- protocols/palworld.js
Added a remap of the value to the one in the screenshot of 491 and 507
> fix: Incorrect numplayers on Palworld

- CHANGELOG.md
- GAMES_LIST.md
- lib/games.js
This closes this issue https://github.com/gamedig/node-gamedig/issues/513
> feat: add Euro Truck Simulator 2 support

- CHANGELOG.md
- GAMES_LIST.md
- lib/games.js
- protocols/eco.js
- protocols/factorio.js
- protocols/index.js
Messed up with commits.
Added Factorio. I was not able to get the tcp ping probing to work on the server/ get a ping at all. Therefore I disabled it.
Should contain all online - non cracked - Factorio servers.
> Add Factorio

- CHANGELOG.md
- protocols/assettocorsa.js
This PR fixes how Assetto Corsa set its `state.numplayers`.
It closes this issue https://github.com/gamedig/node-gamedig/issues/537
—
<details>
<summary>Here's a query response for referencing:</summary>
```
gamedig --type assettocorsa 194.35.12.49:8081 --pretty
{
"name": "Cruisin USA | L.A. Canyons EU 1 | Two Way Traffic on VIP Roads | cruisin.us/discord | Teleports ℹ8081",
"map": "csp/2144/../la_canyons-freeroam",
"raw": {
"carInfo": [
{
"Model": "ks_abarth_595ss_s2",
"Skin": "black/ADAn",
"DriverName": null,
"DriverTeam": null,
"IsRequestedGuid": false,
"IsEntryList": true,
"IsConnected": false
},
{
"Model": "ks_mazda_miata",
"Skin": "19_twilight_blue_lim/ADAn",
"DriverName": null,
"DriverTeam": null,
"IsRequestedGuid": false,
"IsEntryList": true,
"IsConnected": …
```
> fix: Assetto Corsa numplayers

- CHANGELOG.md
- protocols/core.js
Re-write of #477 as OP did not respond to requested changes and comments.
Similar rewrites will be more common from now on as it improves on performance and code readability.
> perf: revise core class and make it cleaner

- CHANGELOG.md
- GAMES_LIST.md
- lib/games.js
Adds Abiotic Factor to the list of games.
> Adding Abiotic Factor support

- CHANGELOG.md
- protocols/minecraftvanilla.js
> feat: Restore Minecraft's favicon

- CHANGELOG.md
- lib/games.js
- protocols/index.js
- protocols/xonotic.js
> fix: xonotic player names being reported as numbers

- CHANGELOG.md
- GAMES_LIST.md
- lib/games.js
> feat: add FOUNDRY support

- .github/workflows/bun.yml
- CHANGELOG.md
- README.md
This PR marks the support for the [Bun](https://bun.sh/) runtime.
Closes #589
> feat: add Bun as a supported runtime

- CHANGELOG.md
- GAMES_LIST.md
- lib/games.js
> Fix alt:V Multiplayer naming as per their branding

- CHANGELOG.md
- GAMES_LIST.md
- lib/games.js
- protocols/index.js
- protocols/vintagestory.js
- protocols/vintagestorymaster.js
Closes #328
Adds the support via a master server.
> feat: add vintage story support

- CHANGELOG.md
- GAMES_LIST.md
- lib/games.js
Implements #612 
Previous PR was messy 🤣
> feat: Add support for rFactor 2, Fix Release years

- CHANGELOG.md
- lib/games.js
> fix: deus ex using wrong protocol

- CHANGELOG.md
- lib/games.js
> fix: soldier of fortune using wrong protocol

- CHANGELOG.md
- GAMES_LIST.md
- lib/games.js
I'll have to find a server for this or someone that has it, might take a while.
Closes #620
> feat: add serious sam the second encounter support

- CHANGELOG.md
- GAMES_LIST.md
- lib/games.js
> feat: add World of Padman support

- CHANGELOG.md
- GAMES_LIST.md
- lib/games.js
- protocols/brokeprotocol.js
- protocols/brokeprotocolmaster.js
- protocols/index.js
Adds support for [BROKE PROTOCOL](https://brokeprotocol.com/)
- Using master server
- Game does require a query port to be accessible but from the logic of the client, it seems only sending data to the master server and not responding to requests
Related issues: #190
Optionally instead of `address` and `port`, `serverId` can be provided.
Setup:
```js
GameDig.query({
type: 'brokeprotocol',
address: '10.0.0.1',
port: 5557,
//serverId: '00000000-0000-0000-0000-000000000001'
```
<details open>
<summary>Example response</summary>
```json
{
"name": "Server Name",
"map": "DCBP",
"raw": {
"name": "&bServer Name",
"version": "1.42",
"ip": "1.0.0.1",
"port": 5557,
"whitelist": false,
"location": "UK",
"validation": "+",
"url": "",
"playerlimit": 16,
"difficulty": 0.5,
"map": { …
```
> feat: add BROKE PROTOCOL support

- CHANGELOG.md
- GAMES_LIST.md
- lib/games.js
Closes #659
This is a recently released game, I have confirmed that this works on the issue author's server but I couldn't find anything related to default ports, will merge when so.
> feat: add Exfil support

- CHANGELOG.md
- GAMES_LIST.md
> docs: Valheim numplayers being always 0 on crossplay servers

- protocols/nadeo.js
Adding Correct Method for TMNF / TMU to get Current Map Info
> Adding CurrentChallengeInfo to get Map Informations

- CHANGELOG.md
- protocols/minetest.js
Minetest changed property name in list
> fix(protocols/minetest): rename ip to address

- CHANGELOG.md
- GAMES_LIST.md
> docs: Arma Reforger does not provide players data

- CHANGELOG.md
- protocols/farmingsimulator.js
Requested on the Discord community by a member.
This was also a TODO.
> feat(game/farmingsimulator): add response to raw object

- CHANGELOG.md
- GAMES_LIST.md
- lib/games.js
- protocols/index.js
- protocols/renown.js
- tools/generate_games_list.js
https://store.steampowered.com/app/1488310/Renown/
Let me know if anything else needed!
> feat: Renown add support

- CHANGELOG.md
- protocols/terraria.js
I noticed that maxplayers was 0 for me and it seems that it wasn't being set.
> fix(protocols/terraria): add missing maxplayers (and raw) to terraria protocol

- CHANGELOG.md
- GAMES_LIST.md
- lib/games.js
- package-lock.json
- package.json
- protocols/core.js
- protocols/index.js
- protocols/sdtd.js
- tools/generate_games_list.js
> feat(protocols/sdtd): add telnet support for players

- CHANGELOG.md
- GAMES_LIST.md
- protocols/sdtd.js
> feat(protocol/sdtd): add optional more data via telnet

- protocols/openttd.js
[gamedig/node-gamedig/issues/265](https://github.com/gamedig/node-gamedig/issues/265)
- rewritten parser (according to current version of network_query.cpp)
- query changed to TCP
- tested with OpenTTD 14.1
> feat(protocol/openttd): update for ^12.0

- protocols/battlefield.js
Closes #703.
**Query debug output with (multiple) skipped packets**
<details>
```
/home/cetteup/.asdf/shims/node /home/cetteup/Dev/node-gamedig/examples/import.mjs
Q#0 Starting
Q#0 Protocol: battlefield
Q#0 Options: {
socketTimeout: 10000000,
attemptTimeout: 10000000,
maxRetries: 1,
stripColors: true,
portCache: true,
noBreadthOrder: false,
ipFamily: 0,
requestPlayers: true,
port: 47200,
protocol: 'battlefield',
type: 'battlefield3',
host: '125.238.206.86',
givenPortOnly: true,
debug: true
}
Q#0 DNS Lookup: 125.238.206.86
Q#0 Raw IP Address: 125.238.206.86
Q#0 125.238.206.86:47200 TCP Connecting
Q#0 125.238.206.86:47200 TCP Connected
Q#0 Registered RTT: 315ms
Q#0 125.238.206.86:47200 TCP-->
Q#0 Buffer length: 27 bytes
00 00 00 00 1b 00 00 00 01 00 00 00 0a 00 00 00 73 65 72 76 65 
s  e  r …
```
> fix(protocol/battlefield): skip non-response packets

- CHANGELOG.md
- GAMES_LIST.md
- lib/games.js
- protocols/index.js
- protocols/scpsl.js
> feat(games): add SCP:SL support
