gamedig/node-gamedig

protocols/teamspeak3.js

Says it all.
(From teamspeak 3 server query manual)
CLIENT_TYPE - Indicates whether the client is a ServerQuery client or not
1 equals server query client.

Teamspeak 3 - avoid ServerQuery clients

---

games.txt

The query port was changed to the game port instead of being offset by
1 as mentioned at http://playrust.com/devblog-74/. Duplicated the line
and renamed the old to rustlegacy for backwards support.

Adjusted Port for Rust to remove offset by 1.

---

games.txt
protocols/squad.js

It seems that squad utilize `Password_b` for passwording servers so the `password` field was incorrect.
This adds a fix after cleanup has been run in a similar fashion to the Battalion 1944 fix.

Add check for Password_b on Squad Servers to correct password field.

---

README.md
bin/gamedig.js
lib/QueryRunner.js

Allows user to disable gamedig's default behavior of adding query attempts using the default query port(-offset).
Adding query attempts for a game's default port or the game port plus a default offset is great for ease of use. However, if you are using gamedig at "scale" and you already know the correct query port these attempts will slow you significantly, especially if maxAttempts is set to anything higher than 1.
An advanced option to disable this default behavior allows anyone who figured the query ports out beforehand to reduce the total query duration and reduce unnecessary CPU load. Also, since a gameQueryPortOffset-based attempt will currently be added regardless of the given port, the resulting attempt might have a port higher than 65535.
- Updated QueryRunner + gamedig binary
- …

Add givenPortOnly user option

---

protocols/gamespy1.js

I was wondering why the `team` property is often empty for one team on a Battlefield 1942 server. Turns out: The current condition for `teamOffByOne` only matches for servers hosting the main game/mod because `gameid` contains the current mod for 1942. Servers hosting `desertcombat` or other mods don't match the condition.
Current condition:
```javascript
const teamOffByOne = data.gameid === 'bf1942';
```
Server info:
```json
{
"name": "Badewiese [Public DC Server]",
"map": "kursk",
"raw": {
"gamename": "bfield1942",
"gamever": "v1.612",
"averagefps": 0,
"content_check": 0,
"dedicated": 2,
"gameid": "desertcombat"
}
```
So, check via `gamename` instead.
```javascript
const teamOffByOne = data.gamename === 'bfield1942';
```
Test server: `78.46.52.115:23000`

Fix teamOffByOne condition for Battlefield 1942

---

package-lock.json
package.json
protocols/openttd.js

This PR removes `moment` and replaces it with `date-fns`
- [`date-fns` repo](https://date-fns.org/)
- [`moment` repo](https://momentjs.com/docs/#/-project-status/)
Since moment is no longer maintained beyond security patches, I took the opportunity to remove it in favor of `date-fns` which is a moment-like alternative. One could argue to use the [temporal api](https://tc39.es/proposal-temporal/docs/) which is in stage 3 of the ecmascript proposal, so if that is desired I can swap over to Temporal instead.
The benfits of date-fns is that it has tree-shaking by default, so we're not importing a whole library. With that, it's also being actively maintained :). We also have types built in!
Please let me know if I should migrate to Temporal instead.

chore(deps): remove moment

---

protocols/minecraft.js

Minecraft resolver now uses registerRtt rather than setting state.ping. This prevents the ping value being overwritten with 0 as shortestRTT is never set.
This fixes the bug reported in #310, which is a regression of #233.

Fixed Minecraft resolver only reporting 0 ping. #310

---

README.md
bin/gamedig.js
lib/DnsResolver.js
lib/QueryRunner.js
protocols/core.js

As mentioned in #306, query may currently fail if the DNS lookup happens to return an IPv6 `AAAA` record instead of an existing IPv4 `A` record. In order to avoid such issues, these changes enables users to directly control which type of record/ip family they accept.
Tested locally with the server mentioned in #306.

Allow direct control of IP family to be returned by DNS lookup

---

README.md
games.txt

As @cyphercolt noted in #282, V Rising uses the Valve protocol on port 27015 (game) and 27016 (query).

Add support for V Rising

---

README.md
games.txt

Another one which turned out to work with the Valve protocol. Game port is 7777, query port is 7776. Tested with below servers.
---------|-----------|----------
193.34.69.12:27260|Onset|1.0.0.0
45.137.151.202:7776|Onset|1.0.0.0
141.95.18.200:7776|Onset|1.0.0.0
141.95.18.200:6776|Onset|1.0.0.0
141.95.18.200:7736|Onset|1.0.0.0
141.95.18.200:7756|Onset|1.0.0.0
141.95.18.200:7746|Onset|1.0.0.0
216.105.171.138:7776|Onset|1.0.0.0

Add support for Onset

---

README.md
games.txt

Yet another Valve protocol game. Only about 25% of the servers in the list responded to my query, not sure why the others did not. Game port is 10999, query is on 27016.
139.162.199.57:12346|Don't Starve Together|438711
46.163.117.215:12348|Don't Starve Together|446029
46.163.117.215:12346|Don't Starve Together|446029
84.201.138.232:12348|Don't Starve Together|382128
84.201.138.232:12346|Don't Starve Together|382128
115.227.0.242:12346|Don't Starve Together|451587
106.53.236.70:27017|Don't Starve Together|446681
118.25.70.57:12348|Don't Starve Together|428872
106.54.76.143:12348|Don't Starve Together|438182
106.54.76.143:12346|Don't Starve Together|438182
106.53.236.70:27016|Don't Starve Together|446681
45.224.128.32:12348|Don't Starve …

Add support for Don't Starve Together

---

README.md
games.txt

As pointed out in #235, Chivalry: Medieval Warfare uses the Valve protocol. Current default game port is 7777, default query port is 7779.
173.244.207.46:21015|Chivalry: Medieval Warfare|1.0.0.1
185.107.96.212:7822|Chivalry: Medieval Warfare|1.0.0.1
51.89.155.137:21019|Chivalry: Medieval Warfare|1.0.0.1
51.91.105.87:21027|Chivalry: Medieval Warfare|1.0.0.1
54.38.29.203:21015|Chivalry: Medieval Warfare|1.0.0.1
51.91.105.87:21019|Chivalry: Medieval Warfare|1.0.0.1
135.181.61.161:7810|Chivalry: Medieval Warfare|1.0.0.1
185.209.177.153:21015|Chivalry: Medieval Warfare|1.0.0.1
199.127.62.226:5556|Chivalry: Medieval Warfare|1.0.0.1
74.91.115.164:27015|Chivalry: Medieval Warfare|1.0.0.1

Add support for Chivalry: Medieval Warfare

---

README.md
games.txt

Valve protocol, mentioned in #223. Game port 27000, query port 27020 (many providers keep the +20 pattern).
Port:IP|Game|Version
92.224.23.151:27020|Avorion|2.3.0.40132
62.104.13.158:27020|Avorion|2.3.0.40132
62.104.66.220:21220|Avorion|2.3.0.40132
62.104.164.82:22620|Avorion|2.3.0.40132
134.255.222.225:21620|Avorion|2.3.0.40132
134.255.222.248:22320|Avorion|2.3.0.40132
195.82.159.223:26808|Avorion|2.3.0.40132
5.83.172.225:59808|Avorion|2.3.0.40132
46.251.235.171:23008|Avorion|2.3.0.40132
5.83.168.252:11508|Avorion|2.3.0.40132

Add support for Avorion

---

README.md
games.txt

Valve protocol. Game/query port is 27015.
34.73.85.163:27015|Black Mesa|100001
34.73.205.169:27015|Black Mesa|100001
104.196.44.133:27015|Black Mesa|100001
34.75.188.20:27015|Black Mesa|100001
142.4.210.168:27026|Black Mesa|100001
144.217.10.50:27037|Black Mesa|100001
186.19.99.1:27023|Black Mesa|100001
43.247.158.122:27019|Black Mesa|100001
45.77.246.174:27015|Black Mesa|100001
45.32.115.189:27015|Black Mesa|100001

Add support for Black Mesa

---

README.md
games.txt

Valve protocol. Default game port is 27015, query port is 27016.
178.254.22.169:27016|Ballistic Overkill|1.5.6.0.1
51.195.235.155:27022|Ballistic Overkill|1.5.6.0.1
51.195.235.155:27016|Ballistic Overkill|1.5.6.0.1
15.204.204.143:27016|Ballistic Overkill|1.5.6.0.1
173.198.254.86:27016|Ballistic Overkill|1.5.6.0.1

Add support for Ballistic Overkill

---

README.md
games.txt

Valve protocol. Game and query port is 4255 by default, as pointed out in #229.
62.104.13.181:4255|Rising World|201911051
62.104.164.59:22809|Rising World (New Version)|202211111
134.255.222.201:23010|Rising World|201911051
195.4.106.15:4255|Rising World|201911051
5.147.199.113:4255|Rising World|201911051
185.250.250.104:4255|Rising World|201911051
51.195.5.215:4254|Rising World (New Version)|202211111
54.37.206.245:4254|Rising World (New Version)|202211111
185.239.237.104:4300|Rising World|201911051
185.239.238.125:4354|Rising World (New Version)|202211111

Add support for Rising World

---

README.md
games.txt

Valve protocol. Listens for both game and query on port 27015.
135.125.140.182:40115|BrainBread 2|1.0.4.4
178.63.16.211:27115|BrainBread 2|1.0.4.4
176.9.10.34:27310|BrainBread 2|1.0.4.4
176.9.10.34:27415|BrainBread 2|1.0.4.4
109.147.165.130:27015|BrainBread 2|1.0.4.4
185.132.42.12:27056|BrainBread 2|1.0.4.4
31.186.250.26:27015|BrainBread 2|1.0.4.4
222.187.222.120:44444|BrainBread 2|1.0.4.4
73.35.73.153:27097|BrainBread 2|1.0.4.4
199.127.62.79:27117|BrainBread 2|1.0.4.4

Add support for BrainBread 2

---

CHANGELOG.md
package-lock.json
package.json
protocols/valve.js

This PR replaces [compressjs](https://www.npmjs.com/package/compressjs) by [seek-bzip](https://www.npmjs.com/package/seek-bzip).
I'm replacing the `compressjs` library as it causes imports problems. The difference between the libraries is that `compressjs` is a library for compression/decompression for a multitude of algorithms, whereas `seek-bzip` does strictly only BZip decoding. 
I'm not really sure about speed but I'd guess its the same.
The usage of `compressjs` was used only in Valve Protocol when decoding compressed packages, unfortunately I couldn't find a server with such compression on, but I compared the output of both versions on some dummy bzip data and they were the same.
Potentially fixes #309, if so it also fixes [homepage#1795](https://github.com/benphelps/homepage/issues/ …

Replace compressjs by seek-bzip

---

CHANGELOG.md
GAMES_LIST.md
games.txt

edit: now 17 as someone added Operation Harsh Doorstop before me 😄 
I had a look through the list of supported games on LinuxGSM to find which ones are not listed in gamedig and added ones that require no extra work apart from adding them to the list. 
The following games added to the list:
* Action Half-Life - Added support (by @dgibbs64).
* Action: Source (2019) - Added support (by @dgibbs64).
* Base Defense (2017) - Added support (by @dgibbs64).
* Blade Symphony (2014) - Added support (by @dgibbs64).
* Brainbread - Added support (by @dgibbs64).
* Deathmatch Classic (2001) - Added support (by @dgibbs64).
* Double Action: Boogaloo (2014) - Added support (by @dgibbs64).
* Dystopia (2005) - Added support (by @dgibbs64).
* Empires Mod (2008) - Added support (by @dgibbs64).
* Fistful of …

17 new games supported

---

CHANGELOG.md
GAMES_LIST.md
games.txt

Closes #356.
This PR does not replace CSGO, as it can still be played, thus it adds a new entry, although it's the same as the old one (the CSGO note needs to be verified.

feat: add cs2 support

---

protocols/epic.js

Fixed the bug where `numplayers` was not populated when performing queries in the game ARK: Survival Ascended
Closes #404 
```
Results {
name: 'BR PVE TribuFu 5x Ascended TheIsland',
map: 'TheIsland_WP',
password: false,
raw: {
deployment: 'ad9a8feffb3b4b2ca315546f038c3ae2',
id: 'ef78140894af4e0bbef1d40733f6f09c',
bucket: 'TestGameMode_C:<None>:TheIsland_WP',
settings: {
maxPublicPlayers: 70,
allowInvites: true,
shouldAdvertise: true,
allowReadById: true,
allowJoinViaPresence: true,
allowJoinInProgress: true,
allowConferenceRoom: false,
checkSanctions: false,
allowMigration: false,
rejoinAfterKick: '',
platforms: null
},
totalPlayers: 2,
openPublicPlayers: 68,
publicPlayers: [],
started: false,
lastUpdated: null,
attributes: {
MINORBUILDID_s: '11',
MODID_l: 0,
CUSTOMSERVERNAME_s: 'BR PVE …
```

fix: ARK: Survival Ascended `numplayers`

---

CONTRIBUTING.md

Closes #64.
The contributing file provides insights regarding adding new lines to this project.
The file is the same one as in [rust-GameDig](https://github.com/gamedig/rust-gamedig/blob/7416d54b144812b63a691335b951843e916c701a/CONTRIBUTING.md), but I added at the bottom the semver rules.

feat: add initial contributing file

---

lib/DnsResolver.js

Fixes #408 by replacing the old IP check with node's built-in check (compatible with Deno).
The IPv6 part of this is mostly irrelevant as I couldn't find any IPv6 game servers and the CLI doesn't handle IPv6 address properly anyway, but I left it in for future proofing.

dns: Use node's built in isIP check instead of regex

---

protocols/asa.js
protocols/epic.js

When cherry picking the commits in #416 , asa and epic protocols ended up using imports, which are not compatible with the other files using require.

fix: Update asa and epic protocols to use node require()

---

CHANGELOG.md

This PR modifies the changelog to tell whats been done in the `4.2.0` intermediary release of #416.
This is a draft as we should merge this after the version gets published.

Update changelog for the 4.2.0 intermediary release

---

protocols/minecraftvanilla.js

The received string length from server is expected to be a byte length whereas if we parse to string first javascript will treat our length as a character length (accounts for UTF multi-byte characters).
This should hopefully fix #434

minecraft: Split vanilla string by bytes instead of characters

---

tools/find-id-changes.js

This tool iterates through the commit history finding commits where lib/games.js has been modified. Whenever it has it loads the before/after state and compares them to generate a list of IDs that were removed/added/changed (changed is based on comparing the name of the game).
The output of this script can then be converted into an object mapping between old IDs and new IDs using a jq one-liner.

tools: Add find ID changes to list changes to game IDs

---

CHANGELOG.md
GAMES_LIST.md
lib/games.js
protocols/beammp.js
protocols/beammpmaster.js
protocols/index.js

Closes #340
I haven't found a way to query the server directly, but as provided in the linked issue (that requested this game), a master server is available, this implementation queries the master server and tries to find the server in the response list (and also processes it a bit if so).

feat: add BeamMP support

---

lib/games.js
protocols/dayz.js
protocols/index.js
protocols/valve.js

DayZ runs on Valve A2S but it is modified quite a bit and their data types needs to be read differently than standard ones, this PR extracts everything dayz related into another protocol file (which still runs on top of the valve protocol file), clears up a lot the cluttered Valve protocol file.

chore: extract dayz from valve

---

.github/workflows/deno.yml
CHANGELOG.md
README.md
lib/GlobalUdpSocket.js
lib/QueryRunner.js

Closes #378.
> Deno `1.39.2` got released which includes added ref/unref for UDP in [Deno#21777](https://github.com/denoland/deno/pull/21777), I think it would be safe to remove the hacky fixes and mention that the Minimum Supported Deno Version is `1.39.2`.
This PR also added a 'Deno compatibility' badge to show the minimum supported deno version.

fix: remove deno hacky fixes

---

protocols/dayz.js

Adds 3 news keys for DayZ:
```js
state.raw.privateHive
state.raw.external
state.raw.official
```
`privateHive` are usually community servers, and `external` does not appear on official servers. `official` is having `false` for both `privateHive` and `external`. I'm guessing this might be the case here, but I'm assuming things, since there's no documentation about this. Tested in several servers.

Add new data for DayZ state

---

CHANGELOG.md
protocols/valve.js

Commit 90e26bb and PR #389 removed the behaviour of adding players with empty data on the `numplayers` count, the valve protocol skipped adding players if their names are empty, some games (such as DayZ) provide players data (time played) but no names. Its better to have partial data than no data at all (beforehand this PR and the mentioned one, the query would return empty players data).

fix(valve): dont skip players with no name

---

GAMES_LIST.md
README.md
bin/gamedig.js
protocols/dayz.js
protocols/valve.js

Hello! This PR is about having all Valve queries required to have a response, otherwise the query will timeout. It will also work alongside `maxAttempts` so that all queries have a response, like suggested here (https://github.com/gamedig/node-gamedig/issues/455).
This PR adds:
- **requestRulesRequired**: boolean - Valve games only. `requestRules` is always required to have a response or the query will timeout. (default false)
- **requestPlayersRequired**: boolean - Valve games only. Querying players is always required to have a response or the query will timeout. Some [games](GAMES_LIST.md) may not provide a players response. (default false)
Also, I'm not sure I got it all working with the new options, so let me know if I should fix something. I tried to add all the code documentation …

feat: Add valve requestRulesRequired & requestPlayersRequired

---

protocols/valve.js

Quick fix to avoid deleting `state.raw.players`, as discussed in this PR (https://github.com/gamedig/node-gamedig/pull/449).

fix: Valve raw.players being deleted

---

CHANGELOG.md
README.md
bin/gamedig.js
lib/QueryRunner.js
protocols/armagetron.js
protocols/doom3.js
protocols/gamespy2.js
protocols/nadeo.js
protocols/quake3.js
protocols/savage2.js
protocols/unreal2.js

Closes #204 (both bots not being processed and the option feature).
Stripping colors defaults to true.

feat: strip colors option and strip bots names in Quake3

---

CHANGELOG.md

This PR adds to the CHANGELOG:
- **requestRulesRequired**: boolean - Valve games only. requestRules is always required to have a response or the query will timeout. (default false)
- **requestPlayersRequired**: boolean - Valve [games](https://github.com/gamedig/node-gamedig/pull/GAMES_LIST.md) only. Querying players is always required to have a response or the query will timeout. Some games may not provide a players response. (default false)
Related to this other PR (https://github.com/gamedig/node-gamedig/pull/458)

chore: add new options to CHANGELOG

---

README.md

Adds a mention about `protocol-` usage in README.
It also closes https://github.com/gamedig/node-gamedig/pull/303.

chore: add 'protocol-' mention on README

---

tools/attempt_protocols.js

Adds a debug option to the 'attempt_protocols' tool. Default is `false`.
`node tools/attempt_protocols 123.123.123.123 debug`

feat: Add debug option to 'attempt_protocols' tool

---

lib/QueryRunner.js
lib/games.js

Hello!
This PR adds an alternative `port_query_offset`. I'm not sure if this all it needs to add an alternative `port_query_offset`, but it worked on the tests I did.
Currently with an option in the game `V Rising`. Related to this issue (https://github.com/gamedig/node-gamedig/issues/438).

feat: make port_query_offset accept a number or an array of numbers

---

CHANGELOG.md
README.md
bin/gamedig.js
lib/QueryRunner.js

Adds the option (enabled by default) to cache ports.
This is the most beneficial when you query the same server (identified by resolved address and port) and it doesn't end up successful on the first attempted port (e.g. specify the query port without `--givenPortOnly` or games that might have multiple offsets (soon to come)).
An example of this would be:
Query `DayZ` server A (with 1 maximum attempt), where we know the query port of that specific server (P1):
1st attempt: specified port + offset (P2)... failure.
2nd attempt: specified port (P1)... success. -- add this port as cached.
Some time later, query the same server (A) with the same port (P1):
1st attempt: cached port... success.
It would only regress if the server changes the query port whilst your service is running, which is …

feat: port caching

---

CHANGELOG.md
GAMES_LIST.md
tools/generate_games_list.js

Adds a note on `GAMES_LIST.md` about EOS Protocol not having players data.
And updates `tools/generate_games_list.js` with this note.
It closes this issue https://github.com/gamedig/node-gamedig/issues/413

chore: add EOS protocol note

---

CHANGELOG.md
GAMES_LIST.md
lib/games.js

Adds the following note about Minecraft. It closes this issue https://github.com/gamedig/node-gamedig/issues/304.
```
Many Minecraft servers do not respond with players data.
```

chore: add Minecraft notes

---

GAMES_LIST.md
lib/games.js
protocols/epic.js
protocols/index.js
protocols/palworld.js

Worth noting that this will only query game servers that are listed in EOS matchmaking. I've noticed at the moment that Palworld, as it's currently booming in popularity, does not include all game servers on it's matchmaking list.
You can also see currently when you host a dedicated server, that the "create session" requests that are made to EOS often fail. When this happens, the game server does not appear in EOS and you can only directly connect in-game.
As far as I'm aware there's not currently a way to directly query a Palworld server.

feat: add support for Palworld

---

protocols/epic.js
protocols/palworld.js

While ASSA returns something in CUSTOMSERVERNAME_s, Palworld returns that on epic as empty, but NAME_s is set with the servername.
Can be tested with:
npx gamedig --debug --type palworld 148.251.89.181:8211
npx gamedig --debug --type asa 148.251.89.181:7783
Both servers are only and from me.
@CosminPerRam Please feel free to improove quality on this fix, you know my skill-level on Javascript 😎

Fix: Palworld results - Name of the server is empty

---

CHANGELOG.md
lib/games.js

Removed instances of `query_port` from the games that were using it and fixed these game's ports (Project Cars, Project Cars 2 and Wurm Unlimited), this was a mistype, as it should have been `port_query`.
Also mentioned in #502.

fix: remove query_port and fix those with the use of it

---

CHANGELOG.md
GAMES_LIST.md
lib/games.js

Support for Enshrouded using Valve protocol.
Closes #505
The game responds successfully when using the valve protocol, and in the server settings it is possible to see the default ports that this PR was based on:
My test server:
```sh
node .\bin\gamedig.js --type enshrouded 189.90.255.6 15637
{
"name": "Enshrouded Server",
"map": "",
"raw": {
"protocol": 17,
"folder": "Enshrouded",
"game": "Enshrouded",
"appId": 1203620,
"numbots": 0,
"listentype": "d",
"environment": "w",
"secure": 0,
"version": "0.0.15.0",
"steamid": "90179849730323478",
"tags": [
"1;487046"
],
"players": []
},
"maxplayers": 16,
"numplayers": 0,
"players": [],
"bots": [],
"queryPort": 15637,
"connect": "189.90.255.6:15636",
"ping": 30
}
```

feat: add support for Enshrouded

---

CHANGELOG.md
GAMES_LIST.md
lib/games.js

Adds support for Duke Nukem Forever 2001. 
Thanks @cetteup for testing and pointing the protocol! See more at https://github.com/gamedig/node-gamedig/issues/298
I'm not 100% sure about and could use a confirmation:
```
release_year: 2022, 
port: 7777, 
port_query_offset: 1
```
—
Example response:
```js
node bin/gamedig --type dnf2001 45.89.125.89 --pretty
{
"name": "The Gravel Pit | EU",
"map": "DM-64-LivesAgain",
"raw": {
"gamename": "dnf",
"gamever": 400,
"minnetver": 400,
"location": 0,
"hostname": "The Gravel Pit | EU",
"hostport": 7777,
"maptitle": "Untitled",
"mapname": "DM-64-LivesAgain",
"gametype": "dnDeathmatchGame",
"numplayers": 0,
"maxplayers": 16,
"gamemode": "openplaying",
"worldlog": true,
"listenserver": false,
"timelimit": 10,
"fraglimit": 35, …
```

feat: add Duke Nukem Forever 2001 support

---

GAMES_LIST.md
tools/generate_games_list.js

This adds EOS Notes on Palworld and The Isle Evrima.
Closes this issue: https://github.com/gamedig/node-gamedig/issues/520
—
Also, would like to have more input on a better solution for detecting this protocol on `tools/generate_games_list.js`
It's currently like this:
```
if (
game.options.protocol === 'epic' || 
game.options.protocol === 'asa' || 
game.options.protocol === 'palworld' || 
game.options.protocol === 'theisleevrima'
) {
notes.push('[EOS Protocol](#epic)')
}
```

chore: Add EOS notes on Palworld and The Isle Evrima

---

CHANGELOG.md
protocols/eco.js

This is my first pull request for this project. So if something is not aligning with the guidelines or coding styles, please give me a hint so I can change it.
The existing code for the Eco game functions correctly. However, it does not use any server protocol; instead, it accesses the web interface (just a plain http request). Many servers employ reverse proxies (or other methods) that cannot connect via the ip. A straightforward solution is to use the host name rather than the IP address. I'm uncertain why the IP address was originally used, given that this is merely a web request.
Additionally, I have included player information in the state.

Updated the eco protocol to include player names and fix problems encountered when using the eco web interface behind a proxy.

---

CHANGELOG.md
protocols/teamspeak2.js

Fix how TeamSpeak 2 protocol set the `state.name`.
It closes this issue https://github.com/gamedig/node-gamedig/issues/543

fix: TeamSpeak2 server name

---

CHANGELOG.md
GAMES_LIST.md
lib/games.js

I couldn't find the official default query port so I'll let it be the default protocol one for now.

feat: add `Nova-Life: Amboise` support

---

CHANGELOG.md
GAMES_LIST.md
lib/games.js
protocols/index.js
protocols/minetest.js

Added support for minetest, which does just use the serverlist under the hood.
Implements initial version for #571

feat: Add Minetest support

---

CHANGELOG.md
GAMES_LIST.md
lib/games.js

Fixes #577
Added forrest as the old id for actual backwards compat. As theforrest was an error from the looks of it.

bug: Remove mispelling legacy entry, add backwards compat.

---

protocols/assettocorsa.js

Fixes #583.
In commit [67e86d3](https://github.com/gamedig/node-gamedig/commit/67e86d3fe883c73e266a9a9e86f6fd93093304d0) I have moved an assignment that took a value from another assignment above it, resulting in all asseto corsa queries to fail because of `undefined`.
We greatly need tests to avoid such mistakes in the future.

fix: assetto corsa failing all queries due to undefined

---

CHANGELOG.md
GAMES_LIST.md
bin/gamedig.js
lib/games.js
protocols/altvmp.js
protocols/core.js
protocols/index.js
protocols/minetest.js

This PR adds support for AltvMP. (#587)
It implements two methods to find the server using the master list at https://api.alt-mp.com/servers
If the `serverId` argument is passed, then a direct lookup can be done at /servers/ID
This does also add a fix to state.connect in general, as if the connect field is manually set, core.js just overrides it. (likely something that was missed when refactored)

Add support for AltvMP

---

CHANGELOG.md
protocols/minecraft.js

Related to #553: @dudekm noted that gamedig cannot extract the name of a minecraft server that runs velocity with the `description` field being color encoded on multiple layers.
Before we would loop through only the top-level `extra` objects, and now we are doing this until the last level (the change could have been easily observed with the recursive solution but I've decided to go with an iterative one).

fix: minecraft velocity name with multiple layers of color encoding

---

CHANGELOG.md
protocols/valve.js

Valve protocol seems to need an option to return rules as bytes.

feat: add a rules bytes return for valve protocol

---

CHANGELOG.md
package-lock.json
package.json

Closes #603.
Replacement of #602.
This PR also updates punycode to avoid a vulnerability.

fix: cheerio breaking the library on new installs and update punycode

---

CHANGELOG.md
protocols/minecraft.js

fix: minecraft vanilla top level description text and mixed cases

---

MIGRATE_IDS.md

I noticed there was a typo in the new terraria ID and fixed it.

docs: fix typo in the new terraria ID

---

CHANGELOG.md
protocols/core.js
protocols/minecraft.js

@mgrimace encountered issues by using the [Homepage](https://github.com/gethomepage/homepage/) project and adding a widget which uses `minecraft`, reported [here](https://github.com/gethomepage/homepage/discussions/3862).
After some debugging we have cloncluded that the bedrock query runs (from logs, as the target server is bedrock edition) and other fails, but the query still fails.
~~Commit [9bd3caa](https://github.com/gamedig/node-gamedig/commit/9bd3caab7b8b45d20349416419ddc36390325782) is the only a contester as why this happens, OP verified this by making the query with the version before this change (`5.0.0-beta.2`) which worked.~~ edit: it was not
Edit:
Commit [6b85c6b](https://github.com/gamedig/node-gamedig/commit/6b85c6bc0b1b3e41dcf3350499af4b21ec43da5e) ~~is also a possiblity~~ …

fix: registerRTT would break successful queries

---

.github/workflows/node.yml

This PR:
* removes 14 (as we no longer support it)
* changes `16.x` to `16.20.0` (which is our minimum supported version)
* adds 20 and 22

ci: node remove 14, set 16 to minimum suported, add 20 and 22

---

lib/DnsResolver.js
package-lock.json
package.json

Suggested by @xCausxn via Discord.
Related: #627
We used the [punycode](https://www.npmjs.com/package/punycode) package just for `toASCII`, Node already has this included via [url.domainToASCII](https://nodejs.org/api/url.html#urldomaintoasciidomain) and does the same thing.

feat: remove punycode package

---

GAMES_LIST.md
tools/generate_games_list.js

Adresses the issue #607. Script will generate the same output as the current list of games.
Anchors are added back to `GAMES_IST.md`, to mark the start and end of the list (to be replaced).

fix: Generate games list with padded delimiter

---

CHANGELOG.md
GAMES_LIST.md
lib/games.js
protocols/index.js
protocols/soldat.js

feat: update Soldat protocol

---

CHANGELOG.md
GAMES_LIST.md
lib/games.js
protocols/index.js
protocols/toxikk.js

Adds support for Toxikk, using Valve protocol + additional properties/settings parsing
Related issues: #628
Example response
```json
{
"name": "The Server Name",
"map": "CC-Artifact_XL",
"raw": {
"protocol": 17,
"folder": "Toxikk",
"game": "cruzade.CRZBloodLust",
"appId": 324810,
"numbots": "0",
"listentype": "d",
"environment": "w",
"secure": 1,
"steamid": "00000000000000000",
"tags": [
"CRZBloodLust"
],
"players": [],
"rules": {
"bIsDedicated": "True",
"bUsesStats": "True",
"NumPublicConnections": "14",
"OwningPlayerId": "0",
"OwningPlayerName": "The Server Owner",
"p1073741825": "CC-Artifact_XL",
"p1073741826": "cruzade.CRZBloodLust",
"p1073741827": "00000000000000000",
"p1073741828": "",
"p1073741829": "",
"p1073741830": "",
"p1073741831": "",
"p1073741832": "", …
```

feat: add Toxikk support

---

CHANGELOG.md
GAMES_LIST.md
lib/games.js
protocols/index.js
protocols/renegadex.js
protocols/renegadexmaster.js
tools/attempt_protocols.js

Adds support for Renegade X, using master server
Related issues: #629
> [!NOTE]  
> Setup and Response updated to reflect made changes during developing this PR.
Setup:
```js
GameDig.query({
type: 'renegade10',
address: '1.0.0.1',
port: 7778
```
Example response
```json
{
"name": "[PREFIX] Server Name",
"map": "CNC-Field",
"raw": {
"Name": "Server Name",
"NamePrefix": "[PREFIX]",
"Current Map": "CNC-Field",
"Bots": 0,
"Players": 12,
"Game Version": "Open Beta 5.84.767",
"Variables": {
"Mine Limit": 24,
"bSteamRequired": false,
"bPrivateMessageTeamOnly": false,
"bPassworded": false,
"bAllowPrivateMessaging": true,
"bRanked": true,
"Game Type": 1,
"Player Limit": 64,
"Vehicle Limit": 20,
"bAutoBalanceTeams": false,
"Team Mode": 6,
"bSpawnCrates": true, …
```

feat: add Renegade X support

---

CHANGELOG.md
protocols/satisfactory.js

#645 added support but the current state of the query response is not that great, it does not provide even the server name or version, this PR makes use of the lightweight query API (which is made via socket packets) to get these information.

feat: Satisfactory add lightweight query

---

CHANGELOG.md
protocols/valve.js

Rust seems to report numplayers incorrectly over A2S. However the tag system exposes the correct number via the cp tag.
GameQ also implements this logic and we have done as well for max players.

fix: Use cp tag for accurate rust player count

---

CHANGELOG.md
GAMES_LIST.md
lib/games.js

feat: add Farming Simulator 25 support

---

CHANGELOG.md
GAMES_LIST.md
protocols/nadeo.js

Closes #634 
~~Servers of Trackmania Nations Forever seem to not respond on `GetCurrentMapInfo` and `GetNextMapInfo` anymore, and I couldn't find a suitable replacement, so this fix removes the assignment of the `map` value (and some next map info in the raw object), made a docs note about this.~~
@Hornochs found a method which contains the map name, merged into this branch by #669
The `version` field is now assigned and the raw object contains more fields that werent added beforehand.
Will merge when I'll also get to test the other games that use the protocol: `Shootmania` and `Trackmania 2`.

fix: nadeo failing queries on map info

---

CHANGELOG.md
GAMES_LIST.md
lib/games.js

A User on the Discord Community Server reported queries not working on their server (Arma: Reforger), turns out you need to configure A2S for it, this adds a note relating this.

docs: add Arma Reforger query setup note

---

CHANGELOG.md
GAMES_LIST.md
lib/games.js

Closes #673, #387 is related.
In #387 we found some server that did provide players data, it turns out these servers were using plugin workarounds which we found in #673. Unfortunately there is no fix for this but to use such a plugin, this PR documents this.

docs(counterstrike2): does not provide player names, note workaround

---

CHANGELOG.md
package-lock.json
package.json

long should be noted in the changelog, fast-xml-parser not as its been added in this release and already mentioned in the doc

chore: update long and fast-xml-parser

---

protocols/brokeprotocolmaster.js
protocols/core.js

This technically adds 2 regressions on this particular protocol:
1. The api check call now uses the state timeout, this could be justified as we'd maybe like to customize it/inline that request with the other's behaviour.
2. Before this, got's `ok` was used, which represents if the request was 'successfully' made, which now consists just checking if the `statusCode` is 200, the other did multiple checks, but I'd say this is fine as this was the only usecase of it in the whole project.

feat(protocol/brokeprotocol): replace explicit got usage

---

CHANGELOG.md
protocols/brokeprotocolmaster.js
protocols/core.js

Closes #650.
We don't make use of the got's internal retry mechanism as we have our own, this would end up making additional unwanted retries.

fix(core/http): remove got internal retry

---

.github/PULL_REQUEST_TEMPLATE/feature.md
.github/PULL_REQUEST_TEMPLATE/fix.md

**Describe the changes**
This particular PR does not need mentioning in the file as its just something related to github and nothing else relating the project (like docs for example, which needs to be mentioned).
Adding templates makes pull requests more concise and helps with standardized procedures of doing so.
**Additional context**
Closes #552.
Template inspired by the existing issue templates.
@xCausxn these are visible only after merging this issue, if you got any suggestions please comment here and I'll do a follow up.

meta: add pr templates

---

CHANGELOG.md
protocols/core.js

Closes #701
This was bound to happen as in:
https://github.com/gamedig/node-gamedig/blob/d3461ffb6167a49518a806b4de782ec438252c7c/protocols/battlefield.js#L115
we would throw inside a callback which wasn't caught.
This is not the case for udpSend as there its already handled.

fix(core): throwing in tcpSend onData callback would crash

---

protocols/farmingsimulator.js

Fixed Problem with vanilla servers. when no mods are activated on the server the mod part is missing in the xml. (https://github.com/gamedig/node-gamedig/issues/722)

fix(game/farmingsimulator): handle possible missing mod attribute

---

CHANGELOG.md
protocols/core.js

Related #734, it'll be a good thing to eventually do this for the entire schema to ensure typing.

fix(core): reassign version to make sure the type is string

---

CHANGELOG.md
GAMES_LIST.md
lib/games.js

* Added new game entry for "Clive Barker's Undying"
* Release year set to 2002
* Configured options with port 7777 and protocol 'gamespy1'
https://en.wikipedia.org/wiki/Clive_Barker%27s_Undying
test server 202.61.207.59:7777

feat(games): add Clive Barker's Undying to game list
